@startuml

class User {
    +username: String
    +email: String
    +playlists: List<Playlist>
    +subscription: Subscription
}

class Artist {
    +name: String
    +albums: List<Album>
}

class Album {
    +title: String
    +songs: List<Song>
    +artist: Artist
}

class PremiumAlbum {
    +exclusiveContent: Boolean
}

class Song {
    +title: String
    +duration: Integer
    +artist: Artist
    +album: Album
    +playlists: List<Playlist>
}


class Playlist {
    +name: String
    +songs: List<Song>
    +user: User
}

class Subscription {
    +type: String
    +price: Float
    +user: User
}

Album <|-- PremiumAlbum : Inherits
User "1" -- "1" Subscription : has >
User "1" -- "n" Playlist : has >
Artist "1" -- "n" Album : has >
Album "1" -- "n" Song : has >
Playlist "n" -- "n" Song : includes >

@enduml